<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>SlayTheSpireLike</RootNamespace>
    <Nullable>disable</Nullable>
    <Company>gewuyou</Company>
    <LangVersion>12</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="script_templates\**\*.cs" />
    <Folder Include="scripts\core\" />
    <Folder Include="scripts\enemies\bat\" />
    <Folder Include="scripts\enemies\carb\" />
    <Folder Include="scripts\player\warrior\" />
    <Compile Remove="scenes\**" />
    <Compile Remove="resources\**" />
    <Compile Remove="addons\**" />
    <Folder Include="scripts\statuses\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="scenes\**" />
    <EmbeddedResource Remove="resources\**" />
    <EmbeddedResource Remove="addons\**" />
  </ItemGroup>
</Project>